### ISSUE TITLE
Error produced with vip.var.fit_2dgaussian

### ISSUE THREAD

**Issue by rbowru** [vortex-exoplanet/VIP#459] opened 2021-09-27 21:20 UTC
Hello, 

I'm running through the new version of the 02_adi_negfc_cc tutorial, and I'm getting an error when running the cell with: 

%matplotlib inline
DF_fit = vip.var.fit_2dgaussian(psf, crop=True, cropsize=9, debug=True, full_output=True)

I've attached the output of the returned error message.  And thank you for updating this section of the tutorial! 

![image](https://user-images.githubusercontent.com/66432460/134986911-63e8e74b-2488-4742-9a3e-70ba5394ed1c.png)

**Comment by VChristiaens** [comment] 2021-09-28 07:26
I believe this issue stems from a change of default behavior in recent versions of `numpy`, which was not predicted in the original versions of VIP but should now be fixed in versions 1.0.0 onwards - I cannot reproduce your bug with the latest version.

**Comment by rbowru** [comment] 2021-10-01 21:18
Thanks!  Updating my VIP version fixed this error

**Closed** 2021-10-04 14:21 UTC
